### ISSUE TITLE
Report download button broke again

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-web#1324]
Error:
```
undefined method `select_pipeline_run' for #<Project:0x000000000117e2a0>
/usr/local/bundle/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
/app/app/lib/report_helper.rb:962:in `report_csv_from_params'
/app/app/models/project.rb:88:in `block in bulk_report_csvs_from_params'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
/app/app/models/project.rb:87:in `bulk_report_csvs_from_params'
/app/app/jobs/generate_project_reports_csv.rb:5:in `perform'
```

**Comment by cdebourcy** [comment]
This is because select_pipeline_run is defined only in the samples controller, but here the call originates from the project controller. I think select_pipeline_run should be moved to report_helper and params should be passed as an additional argument.
